project:
  type: website
  output-dir: docs

website:
  title: "personal website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: Data-viz.qmd
        text: Data Visualization
      - href: reflection.qmd
        text: Reflection

format:
  html:
    theme:
      - journal
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



